'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Bitacora
    
    '''<summary>
    '''inputDateFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inputDateFrom As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''inputDateTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inputDateTo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''inputCriticidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inputCriticidad As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''userList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents userList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''showBtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents showBtn As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnBorrarFiltros control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBorrarFiltros As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''bitacoraGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bitacoraGrid As Global.System.Web.UI.WebControls.GridView
End Class
