'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class masterPrincipal
    
    '''<summary>
    '''head control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents head As Global.System.Web.UI.WebControls.ContentPlaceHolder
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''inputSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inputSearch As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl
    
    '''<summary>
    '''btnIngresarNavBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnIngresarNavBar As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''inputEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inputEmail As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''inputPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inputPassword As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnIngresar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnIngresar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''username control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents username As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ProfileNavBarBtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProfileNavBarBtn As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''navbarSeparador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents navbarSeparador As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''logoutOption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents logoutOption As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LogoutBtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LogoutBtn As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''divEncuesta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divEncuesta As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divEncuestaPreguntas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divEncuestaPreguntas As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''encuestaText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents encuestaText As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''rptEncuestaOpciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptEncuestaOpciones As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''divEncuestaChart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divEncuestaChart As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''chartEncuesta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chartEncuesta As Global.System.Web.UI.DataVisualization.Charting.Chart
    
    '''<summary>
    '''btnCloseEncuesta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCloseEncuesta As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''sidebar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sidebar As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnProfileSidebar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnProfileSidebar As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnABMNoticasSideBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnABMNoticasSideBar As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnMisPublicacionesSideBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMisPublicacionesSideBar As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnSegBackupSideBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSegBackupSideBar As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnSegRestoreSideBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSegRestoreSideBar As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnSegUsuariosSideBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSegUsuariosSideBar As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnSegBitacoraSideBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSegBitacoraSideBar As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnCuentaCorrienteSideBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCuentaCorrienteSideBar As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnAdminCuentaCorrienteSideBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAdminCuentaCorrienteSideBar As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnSegRolesSideBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSegRolesSideBar As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnABMPublicacionesSideBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnABMPublicacionesSideBar As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnReportesSideBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReportesSideBar As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnABMEncuestasSideBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnABMEncuestasSideBar As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnPublicidadSideBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPublicidadSideBar As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnClasificadosSideBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClasificadosSideBar As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''AdRotator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AdRotator1 As Global.System.Web.UI.WebControls.AdRotator
    
    '''<summary>
    '''modalMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents modalMsg As Global.Index.ModalError
    
    '''<summary>
    '''ContentPlaceHolder1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentPlaceHolder1 As Global.System.Web.UI.WebControls.ContentPlaceHolder
    
    '''<summary>
    '''btnLogoutModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLogoutModal As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''divScriptmanager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divScriptmanager As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager
End Class
