'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Reportes
    
    '''<summary>
    '''btnFichas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFichas As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnGanancias control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGanancias As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnChats control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnChats As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnEncuestas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEncuestas As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''divTiempoDeRespuesta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTiempoDeRespuesta As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''dpDesdeTiempoDeRespuesta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dpDesdeTiempoDeRespuesta As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dpHastaTiempoDeRespuesta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dpHastaTiempoDeRespuesta As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnFiltrarTiempoDeRespuesta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFiltrarTiempoDeRespuesta As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''divTiempoDeRespuesta_Content control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTiempoDeRespuesta_Content As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divPreguntaTiempoDeRespuesta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPreguntaTiempoDeRespuesta As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divChartTiempoDeRespuesta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divChartTiempoDeRespuesta As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''chartTiempoDeRespuesta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chartTiempoDeRespuesta As Global.System.Web.UI.DataVisualization.Charting.Chart
    
    '''<summary>
    '''divEncuestas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divEncuestas As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''grdEncuestas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdEncuestas As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''divEncuestas_Content control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divEncuestas_Content As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divPreguntaEncuesta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPreguntaEncuesta As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divChartEncuesta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divChartEncuesta As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''chartEncuesta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chartEncuesta As Global.System.Web.UI.DataVisualization.Charting.Chart
    
    '''<summary>
    '''divFichasDeOpinion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divFichasDeOpinion As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''grdFichasDeOpinion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdFichasDeOpinion As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''divFichasDeOpinion_Content control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divFichasDeOpinion_Content As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divPreguntaFichaDeOpinion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPreguntaFichaDeOpinion As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divChartFichaDeOpinion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divChartFichaDeOpinion As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''chartFichaDeOpinion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chartFichaDeOpinion As Global.System.Web.UI.DataVisualization.Charting.Chart
    
    '''<summary>
    '''divGanancias control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divGanancias As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''dpDesdeGanancias control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dpDesdeGanancias As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnFiltrarGanancias control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFiltrarGanancias As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''dpHastaGanancias control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dpHastaGanancias As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlMes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMes As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnMensualGanancias control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMensualGanancias As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnGananciasYTD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGananciasYTD As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''divGanancias_Content control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divGanancias_Content As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ChartGanancias control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChartGanancias As Global.System.Web.UI.DataVisualization.Charting.Chart
    
    '''<summary>
    '''divGananciasResultados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divGananciasResultados As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblTotalMensual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalMensual As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnVerListado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnVerListado As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''divPreguntaGanancias control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPreguntaGanancias As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''gridGanacias control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridGanacias As Global.System.Web.UI.WebControls.GridView
End Class
