'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class chatComment
    
    '''<summary>
    '''textComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents textComment As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''fpregunta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fpregunta As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''respuesta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents respuesta As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''textRespuesta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents textRespuesta As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''frespuesta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frespuesta As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''inputRespuesta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inputRespuesta As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnEnviarRespuesta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEnviarRespuesta As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnResponder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnResponder As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''id control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id As Global.System.Web.UI.WebControls.HiddenField
End Class
